name: Terraform CI/CD

on:
  pull_request:
    paths:
      - 'eks-bootstrap/**'
      - 'environments/**'
      - '.github/workflows/terraform.yml'
  push:
    branches:
      - main
    paths:
      - 'eks-bootstrap/**'
      - 'environments/**'
      - '.github/workflows/terraform.yml'

env:
  TF_VERSION: 1.6.0
  AWS_REGION: us-east-1
  WORKING_DIR: eks-bootstrap

jobs:
  fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Terraform Format
        run: terraform -chdir=${{ env.WORKING_DIR }} fmt -check

  lint:
    name: Terraform Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v1
      - name: Run TFLint
        run: tflint ${{ env.WORKING_DIR }}

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform Init
        run: terraform -chdir=${{ env.WORKING_DIR }} init -backend-config=../environments/dev/backend.hcl
      - name: Terraform Plan
        run: terraform -chdir=${{ env.WORKING_DIR }} plan -var-file=../environments/dev/backend.hcl

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: prod
    if: github.ref == 'refs/heads/main'
    needs: [fmt, lint, plan]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform Init
        run: terraform -chdir=${{ env.WORKING_DIR }} init -backend-config=../environments/prod/backend.hcl
      - name: Terraform Apply
        run: terraform -chdir=${{ env.WORKING_DIR }} apply -auto-approve -var-file=../environments/prod/backend.hcl